#!/usr/bin/env python3
"""Regenerate keaton/assets/pixel_me.py from a source image.

Usage:
    python scripts/gen_pixel_art.py [IMAGE] [WIDTH] [HEIGHT]

Defaults: IMAGE=$KEATON_SPLASH_IMAGE or ~/Downloads/keaton.JPG, 27x48.
HEIGHT must be even (each terminal cell renders two vertical pixels).
Requires Pillow (`pip install pillow`).
"""
import base64
import os
import sys
from pathlib import Path

DEFAULT_IMAGE = os.environ.get(
    "KEATON_SPLASH_IMAGE", str(Path.home() / "Downloads" / "keaton.JPG")
)
OUT = Path(__file__).resolve().parent.parent / "keaton" / "assets" / "pixel_me.py"


def main() -> int:
    try:
        from PIL import Image, ImageEnhance
    except ImportError:
        print("Pillow is required: pip install pillow", file=sys.stderr)
        return 1

    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_IMAGE
    w = int(sys.argv[2]) if len(sys.argv) > 2 else 27
    h = int(sys.argv[3]) if len(sys.argv) > 3 else 48
    if h % 2:
        h += 1  # keep even for half-block rendering

    if not Path(src).exists():
        print(f"Image not found: {src}", file=sys.stderr)
        return 1

    im = Image.open(src).convert("RGB").resize((w, h), Image.LANCZOS)
    im = ImageEnhance.Color(im).enhance(1.18)
    im = ImageEnhance.Contrast(im).enhance(1.06)
    raw = im.tobytes()
    b64 = base64.b64encode(raw).decode()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '"""Pixel-art portrait for the Keaton startup splash.\n\n'
        "Auto-generated by scripts/gen_pixel_art.py.\n"
        "DATA is base64-encoded row-major RGB bytes (WIDTH*HEIGHT*3).\n"
        '"""\n\n'
        f"WIDTH = {w}\n"
        f"HEIGHT = {h}\n"
        f'DATA = "{b64}"\n'
    )
    print(f"Wrote {OUT} ({w}x{h}, {len(b64)} b64 chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
